// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Proof Pass API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi


import (
	"time"
)



type UpdateEventRequest struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`

	AdminCode string `json:"admin_code,omitempty"`

	StartDate time.Time `json:"start_date,omitempty"`

	EndDate time.Time `json:"end_date,omitempty"`
}

// AssertUpdateEventRequestRequired checks if the required fields are not zero-ed
func AssertUpdateEventRequestRequired(obj UpdateEventRequest) error {
	return nil
}

// AssertUpdateEventRequestConstraints checks if the values respects the defined constraints
func AssertUpdateEventRequestConstraints(obj UpdateEventRequest) error {
	return nil
}
