/* tslint:disable */
/* eslint-disable */
/**
 * Proof Pass API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PutEmailCredentialRequest
 */
export interface PutEmailCredentialRequest {
    /**
     *
     * @type {string}
     * @memberof PutEmailCredentialRequest
     */
    data?: string;
    /**
     *
     * @type {Date}
     * @memberof PutEmailCredentialRequest
     */
    issuedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof PutEmailCredentialRequest
     */
    expireAt?: Date;
}

/**
 * Check if a given object implements the PutEmailCredentialRequest interface.
 */
export function instanceOfPutEmailCredentialRequest(
    value: object,
): value is PutEmailCredentialRequest {
    return true;
}

export function PutEmailCredentialRequestFromJSON(
    json: any,
): PutEmailCredentialRequest {
    return PutEmailCredentialRequestFromJSONTyped(json, false);
}

export function PutEmailCredentialRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PutEmailCredentialRequest {
    if (json == null) {
        return json;
    }
    return {
        data: json['data'] == null ? undefined : json['data'],
        issuedAt:
            json['issued_at'] == null ? undefined : new Date(json['issued_at']),
        expireAt:
            json['expire_at'] == null ? undefined : new Date(json['expire_at']),
    };
}

export function PutEmailCredentialRequestToJSON(
    value?: PutEmailCredentialRequest | null,
): any {
    if (value == null) {
        return value;
    }
    return {
        data: value['data'],
        issued_at:
            value['issuedAt'] == null
                ? undefined
                : value['issuedAt'].toISOString(),
        expire_at:
            value['expireAt'] == null
                ? undefined
                : value['expireAt'].toISOString(),
    };
}
