apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - secrets.yaml

# patch config maps
configMapGenerator:
  - behavior: merge
    literals:
      - BACKEND_ISSUERCHAINID=11155111
      - BACKEND_ENABLELOGINEMAIL=false
      - BACKEND_RESTPORT=3000
      - BACKEND_POSTGRESUSERNAME=postgres
      - BACKEND_JWTEXPIRESSEC=36000
      - BACKEND_ETHRPCURL=https://rpc.ankr.com/eth
      - BACKEND_CONTEXTREGISTRYADDR=0x42D6444840842F0484C1624899c9a3E835738592

    name: backend
    namespace: app
  - behavior: merge
    literals:
      - ENV=local
    name: frontend
    namespace: app
  - behavior: merge
    literals:
      - ISSUER_ID=125344402375953606533377270523694284815265854046 # Demo issuer - https://etherscan.io/tx/0xfbf58513352fe0dc899544b66013adbacb90437210e0008ceeb7b9c9ecec5bdd#eventlog
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    name: issuer
    namespace: app
  - behavior: merge
    literals:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    name: postgres
    namespace: app
