openapi: 3.0.3
info:
  title: Proof Pass API
  version: 0.1.0
  license:
    { name: Apache 2.0, url: https://www.apache.org/licenses/LICENSE-2.0.html }
servers:
  - url: http://localhost:3000/v1
    description: Localhost development server
  - url: https://api.proofpass.io/v1
    description: Production server
paths:
  /health:
    get:
      summary: Check the health of the API
      responses:
        "200":
          description: The API is healthy
  /events:
    post:
      summary: Create a new event
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventRequest"
      responses:
        "201":
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    get:
      summary: Get list of events
      responses:
        "200":
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /events/{eventId}:
    put:
      summary: Update an event
      security:
        - bearerAuth: []
      parameters:
      - name: eventId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
      responses:
        "200":
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    get:
      summary: Get event details
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
  /events/{eventId}/request-ticket-credential:
    post:
      summary: Request a new ticket credential for an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Ticket credential generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnencryptedTicketCredential"
  /events/{eventId}/attendance:
    post:
      summary: Record attendance for an event
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordAttendanceRequest"
      responses:
        "201":
          description: Attendance recorded successfully

  /user/request-verification-code:
    post:
      summary: Request an email verification code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEmailVerificationRequest"
      responses:
        "200":
          description: Verification code sent successfully
  /user/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /user/me:
    get:
      summary: Get user details
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user/update:
    put:
      summary: Update user details
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: User details updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user/me/email-credential:
    get:
      summary: Get user email credential
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User email credential retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmailCredential"
    put:
      summary: Store user email credential with encrypted data
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutEmailCredentialRequest"
      responses:
        "201":
          description: Email credential stored successfully
  /user/me/ticket-credentials:
    get:
      summary: Get user ticket credentials
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User credentials retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketCredential"
  /user/me/ticket-credential:
    put:
      summary: Store user ticket credential with encrypted data
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutTicketCredentialRequest"
      responses:
        "201":
          description: Ticket credential stored successfully
  /user/me/request-email-credential:
    post:
      summary: Generate a new email credential
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Email credential generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnencryptedEmailCredential"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        chain_id:
          type: string
        context_id:
          type: string
        context_string:
          type: string
        issuer_key_id:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
    RecordAttendanceRequest:
      type: object
      properties:
        type:
          type: string
        context:
          type: string
        nullifier:
          type: string
        key_id:
          type: string
        event_id:
          type: string
        admin_code:
          type: string
    UserEmailVerificationRequest:
      type: object
      properties:
        email:
          type: string
    UserLogin:
      type: object
      properties:
        email:
          type: string
        code:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
        is_encrypted:
          type: boolean
        created_at:
          type: string
          format: date-time
    UserUpdate:
      type: object
      properties:
        identity_commitment:
          type: string
        encrypted_internal_nullifier:
          type: string
        encrypted_identity_secret:
          type: string
    EmailCredential:
      type: object
      properties:
        id:
          type: string
        identity_commitment:
          type: string
        data:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    PutEmailCredentialRequest:
      type: object
      properties:
        data:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    UnencryptedEmailCredential:
      type: object
      properties:
        credential:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    TicketCredential:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        event_id:
          type: string
        data:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    PutTicketCredentialRequest:
      type: object
      properties:
        event_id:
          type: string
        data:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    UnencryptedTicketCredential:
      type: object
      properties:
        event_id:
          type: string
        credential:
          type: string
        issued_at:
          type: string
          format: date-time
        expire_at:
          type: string
          format: date-time
    CreateEventRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
    UpdateEventRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
        admin_code:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
